//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleFileDialog.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleFileDialog.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Authentication に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Common に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If set, continue executing the remaining activities even if the current activity has failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ContinueOnError に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Displays a dialog to select a file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenFileDialog_Description {
            get {
                return ResourceManager.GetString("OpenFileDialog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a Dialog for open or save. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenFileDialog_DialogType_Description {
            get {
                return ResourceManager.GetString("OpenFileDialog_DialogType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DialogType に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenFileDialog_DialogType_DisplayName {
            get {
                return ResourceManager.GetString("OpenFileDialog_DialogType_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OpenFileDialog に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenFileDialog_DisplayName {
            get {
                return ResourceManager.GetString("OpenFileDialog_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a displayable file type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenFileDialog_FileType_Description {
            get {
                return ResourceManager.GetString("OpenFileDialog_FileType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FileType に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenFileDialog_FileType_DisplayName {
            get {
                return ResourceManager.GetString("OpenFileDialog_FileType_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter the initial folder path or file path optionally に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenFileDialog_InitialPath_Description {
            get {
                return ResourceManager.GetString("OpenFileDialog_InitialPath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   InitialPath に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenFileDialog_InitialPath_DisplayName {
            get {
                return ResourceManager.GetString("OpenFileDialog_InitialPath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   selected file path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenFileDialog_SelectedFilePath_Description {
            get {
                return ResourceManager.GetString("OpenFileDialog_SelectedFilePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SelectedFilePath に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenFileDialog_SelectedFilePath_DisplayName {
            get {
                return ResourceManager.GetString("OpenFileDialog_SelectedFilePath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter the title of the dialog optionally に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenFileDialog_Title_Description {
            get {
                return ResourceManager.GetString("OpenFileDialog_Title_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenFileDialog_Title_DisplayName {
            get {
                return ResourceManager.GetString("OpenFileDialog_Title_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Displays a dialog to save file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveFileDialog_Description {
            get {
                return ResourceManager.GetString("SaveFileDialog_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SaveFileDialog に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveFileDialog_DisplayName {
            get {
                return ResourceManager.GetString("SaveFileDialog_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select a displayable file type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveFileDialog_FileType_Description {
            get {
                return ResourceManager.GetString("SaveFileDialog_FileType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FileType に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveFileDialog_FileType_DisplayName {
            get {
                return ResourceManager.GetString("SaveFileDialog_FileType_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter the initial folder path or file path optionally に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveFileDialog_InitialPath_Description {
            get {
                return ResourceManager.GetString("SaveFileDialog_InitialPath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   InitialPath に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveFileDialog_InitialPath_DisplayName {
            get {
                return ResourceManager.GetString("SaveFileDialog_InitialPath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   selected file path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveFileDialog_SelectedFilePath_Description {
            get {
                return ResourceManager.GetString("SaveFileDialog_SelectedFilePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SelectedFilePath に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveFileDialog_SelectedFilePath_DisplayName {
            get {
                return ResourceManager.GetString("SaveFileDialog_SelectedFilePath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter the title of the dialog optionally に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveFileDialog_Title_Description {
            get {
                return ResourceManager.GetString("SaveFileDialog_Title_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveFileDialog_Title_DisplayName {
            get {
                return ResourceManager.GetString("SaveFileDialog_Title_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Displays a dialog to select a folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectFolder_Description {
            get {
                return ResourceManager.GetString("SelectFolder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SelectFolderDialog に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectFolder_DisplayName {
            get {
                return ResourceManager.GetString("SelectFolder_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter the Initial folder path optionally に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectFolder_InitialFolderPath_Description {
            get {
                return ResourceManager.GetString("SelectFolder_InitialFolderPath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   InitialFolderPath に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectFolder_InitialFolderPath_DisplayName {
            get {
                return ResourceManager.GetString("SelectFolder_InitialFolderPath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Selected folder path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectFolder_SelectedFolderPath_Description {
            get {
                return ResourceManager.GetString("SelectFolder_SelectedFolderPath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SelectedFolderPath に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectFolder_SelectedFolderPath_DisplayName {
            get {
                return ResourceManager.GetString("SelectFolder_SelectedFolderPath_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter the title of the dialog optionally に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectFolder_Title_Description {
            get {
                return ResourceManager.GetString("SelectFolder_Title_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SelectFolder_Title_DisplayName {
            get {
                return ResourceManager.GetString("SelectFolder_Title_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeout (milliseconds) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The activity timed out and was canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide a value either for {0} or {1}, but not both. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide values for both {0} and {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot be used outside of a {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide a value for {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
    }
}
